// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1-Q-fy3509FN_-CcH_C9S2sEyzxWQEUg',
    appId: '1:817818459967:web:d03cac80389c3dd5f07d8a',
    messagingSenderId: '817818459967',
    projectId: 'workout-tracker-951e8',
    authDomain: 'workout-tracker-951e8.firebaseapp.com',
    storageBucket: 'workout-tracker-951e8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOrI7I3xDuwtn-vvmv3cxeoz9z_53lEAo',
    appId: '1:817818459967:android:feae36670928cc51f07d8a',
    messagingSenderId: '817818459967',
    projectId: 'workout-tracker-951e8',
    storageBucket: 'workout-tracker-951e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqKcchWMgwJTUD45VYwO2eOoI6lt_xNw4',
    appId: '1:817818459967:ios:69e4eba179d4069ff07d8a',
    messagingSenderId: '817818459967',
    projectId: 'workout-tracker-951e8',
    storageBucket: 'workout-tracker-951e8.appspot.com',
    iosBundleId: 'com.example.workoutTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqKcchWMgwJTUD45VYwO2eOoI6lt_xNw4',
    appId: '1:817818459967:ios:5a393dda2a1b3e02f07d8a',
    messagingSenderId: '817818459967',
    projectId: 'workout-tracker-951e8',
    storageBucket: 'workout-tracker-951e8.appspot.com',
    iosBundleId: 'com.example.workoutTracker.RunnerTests',
  );
}
